### ISSUE TITLE
Error with .JsonReaderException: 'n' is invalid within a number, and seems to be a sign error and expected a digit 

### ISSUE THREAD

**Issue by SCP-049-J** [PrincessRTFM/StarboundInventoryUpdater#2]
hello, i downloaded the mod you made to increase inventory's space as an alternative to the Json way but i had trouble with it so that's why i switched to your mod, after launching it, i got this error 

System.Text.Json.JsonReaderException: 'n' is invalid within a number, immediately after a sign character ('+' or '-'). Expected a digit ('0'-'9'). LineNumber: 12350 | BytePositionInLine: 78.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.TryGetNumber(ReadOnlySpan`1 data, Int32& consumed)
   at System.Text.Json.Utf8JsonReader.ConsumeNumber()
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ConsumeNextTokenUntilAfterAllCommentsAreSkipped(Byte marker)
   at System.Text.Json.Utf8JsonReader.ConsumeNextToken(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.JsonDocument.Parse(ReadOnlySpan`1 utf8JsonSpan, JsonReaderOptions readerOptions, MetadataDb& database, StackRowStack& stack)
   at System.Text.Json.JsonDocument.ParseUnrented(ReadOnlyMemory`1 utf8Json, JsonReaderOptions readerOptions, JsonTokenType tokenType)
   at System.Text.Json.JsonDocument.ParseValue(ReadOnlyMemory`1 json, JsonDocumentOptions options)
   at System.Text.Json.Nodes.JsonNode.Parse(String json, Nullable`1 nodeOptions, JsonDocumentOptions documentOptions)
   at StarboundInventoryUpdater.Core.Main(String[] args) in D:\a\StarboundInventoryUpdater\StarboundInventoryUpdater\StarboundInventoryUpdater\Core.cs:line 98

Aborting, please send this log to the developer.
Press any key to close this window.

it is the first time i do a bug report so i hope it's good enough and i showed what was needed.  thanks in advance

**Comment by VariableVixen** [comment]
I need the _full_ log, not just the error. The entire output on the terminal window. Please also select the entire log and click the formatting button for "add code", to format it nicely so I can read it more easily.

**Comment by SCP-049-J** [comment]
sorry i'll do that again and select the entire log 

$ "e:\steam\steamapps\common\Starbound\win32\dump_versioned_json.exe"
  "e:\steam\steamapps\common\Starbound\storage\player\40bb41696474283322331032ca0cf5f9.player"
  "C:\Users\Noe\AppData\Local\Temp\tmpA361.tmp"
^ 0/338
| 246769,3:inf,10:4294967295
= Micah, male lamia
? objectBag   = 120/120
? materialBag = 120/120
? foodBag     = 120/120
? reagentBag  = 120/120
? mainBag     = 120/120
? armoryBag   = 120/120
? farmBag     = 120/120
? vehicleBag  = 120/120
? objectBag2  = 120/120
? hobbyBag    = 120/120
$ "e:\steam\steamapps\common\Starbound\win32\make_versioned_json.exe"
  "C:\Users\Noe\AppData\Local\Temp\tmpA361.tmp"
  "C:\Users\Noe\AppData\Local\Temp\tmpA362.tmp"
^ 0/80
> 40bb41696474283322331032ca0cf5f9
+ 447ms

& C:\Users\Noe\AppData\Local\Temp\tmpA528.tmp
& C:\Users\Noe\AppData\Local\Temp\tmpA529.tmp
< 4d5986f122238d4c5ccec2273dd22a1a
$ "e:\steam\steamapps\common\Starbound\win32\dump_versioned_json.exe"
  "e:\steam\steamapps\common\Starbound\storage\player\4d5986f122238d4c5ccec2273dd22a1a.player"
  "C:\Users\Noe\AppData\Local\Temp\tmpA528.tmp"
^ 0/1876
| 3005173,3:inf,10:4294967295
: C:\Users\Noe\AppData\Local\Temp\tmp94B7.tmp
: C:\Users\Noe\AppData\Local\Temp\tmp94B8.tmp
: C:\Users\Noe\AppData\Local\Temp\tmpA10D.tmp
: C:\Users\Noe\AppData\Local\Temp\tmpA10E.tmp
: C:\Users\Noe\AppData\Local\Temp\tmpA361.tmp
: C:\Users\Noe\AppData\Local\Temp\tmpA362.tmp
: C:\Users\Noe\AppData\Local\Temp\tmpA528.tmp
: C:\Users\Noe\AppData\Local\Temp\tmpA529.tmp

System.Text.Json.JsonReaderException: 'n' is invalid within a number, immediately after a sign character ('+' or '-'). Expected a digit ('0'-'9'). LineNumber: 12350 | BytePositionInLine: 78.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.TryGetNumber(ReadOnlySpan`1 data, Int32& consumed)
   at System.Text.Json.Utf8JsonReader.ConsumeNumber()
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ConsumeNextTokenUntilAfterAllCommentsAreSkipped(Byte marker)
   at System.Text.Json.Utf8JsonReader.ConsumeNextToken(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.JsonDocument.Parse(ReadOnlySpan`1 utf8JsonSpan, JsonReaderOptions readerOptions, MetadataDb& database, StackRowStack& stack)
   at System.Text.Json.JsonDocument.ParseUnrented(ReadOnlyMemory`1 utf8Json, JsonReaderOptions readerOptions, JsonTokenType tokenType)
   at System.Text.Json.JsonDocument.ParseValue(ReadOnlyMemory`1 json, JsonDocumentOptions options)
   at System.Text.Json.Nodes.JsonNode.Parse(String json, Nullable`1 nodeOptions, JsonDocumentOptions documentOptions)
   at StarboundInventoryUpdater.Core.Main(String[] args) in D:\a\StarboundInventoryUpdater\StarboundInventoryUpdater\StarboundInventoryUpdater\Core.cs:line 98

Aborting, please send this log to the developer.
Press any key to close this window.
 
here is the full log now, my bad for the first time i didn't knew

**Comment by VariableVixen** [comment]
Can you upload your `e:\steam\steamapps\common\Starbound\storage\player\4d5986f122238d4c5ccec2273dd22a1a.player` file? I need to see what's around the invalid part.

**Comment by SCP-049-J** [comment]
[4d5986f122238d4c5ccec2273dd22a1a.zip](https://github.com/PrincessRTFM/StarboundInventoryUpdater/files/12113926/4d5986f122238d4c5ccec2273dd22a1a.zip)

here is the file, i hope i did it correctly

**Comment by VariableVixen** [comment]
Have you actually loaded into a world with that character? Because when I use the Starbound dev tool to convert it to JSON, I get this:
```json
{
  "id" : "PlayerEntity",
  "version" : 0,
  "content" : null
}
```
My own player file generates about a megabyte of JSON instead, and when I look at [your player file](https://github.com/PrincessRTFM/StarboundInventoryUpdater/assets/8753564/f8f20d13-7fad-42ec-b2a4-8df58a249dc3) and [my player file](https://github.com/PrincessRTFM/StarboundInventoryUpdater/assets/8753564/89356aba-9990-4bc1-bdd4-57edd6f143eb) side-by-side as raw bytes, yours looks like a lot of meaningless junk data.

**Comment by SCP-049-J** [comment]
huh, i don't think i used that character in a while since i started to replay starbound a few weeks back, guess i could just delete that one if it fixes the issue

**Comment by VariableVixen** [comment]
That particular character file _seems_ to be invalid, but loading it in the game might (depending on the game devs) update it and fix the issue.

The problem is that, for whatever reason, the official dev-created converter to turn the character save file into a JSON file is apparently unable to process that particular character, meaning there's nothing for this tool to operate on. If that character can be loaded by the game itself, that might cause the game to save an updated (fixed) version, which you could then retry with. If it can't be loaded by the game... well, that would mean it's definitely broken and there's not really anything you can do about it, I'm afraid.

It's up to you if you want to try it or just delete the character.

**Comment by SCP-049-J** [comment]
alright i'll see about it and think for a bit, also, after i'll re-launch your program, will i need to download bk3k's mod after or will not need to have it? because i wanna make sure i don't break my game or my characters. thanks in advance :)

**Comment by VariableVixen** [comment]
You WILL need bk3k's expanded inventory mod, the 120 slot version, for ALL characters after running this tool. There is currently no way to limit it to only particular ones, so you'll need to back up characters you don't want affected, then copy them back after running this. Somewhere on my todo list is allowing character selection, reverting the change, and maybe offering different inventory sizes, but it's down there a ways.

**Comment by SCP-049-J** [comment]
alr thanks again for the help, and it finally worked!! :D, now i won't need to worry about not having inventory space! tysm!
